Results:
  save_results: True
  save_dir: "/mnt/nas_10/group/hongjia/PanopticGS-test"
  save_debug: True # True False

model_params:
  sh_degree: 0
  primitive_level_feat: False
  primitive_level_feat_dim: 16 # 3
  white_background: False
  data_device: "cuda"

Dataset:
  dataset_path: "/mnt/nas_10/group/hongjia/datasets/Replica"
  generated_floder: '/mnt/nas_10/group/hongjia/Replica_generated'
  # generated_floder: '/mnt/nas_10/group/hongjia/datasets/Replica_generated/640x360/2D_masks'
  # mask_name: "semantic-sam"
  mask_name: "sam"
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.05
  type: 'replica'
  Calibration:
    fx: 600.0
    fy: 600.0
    cx: 599.5
    cy: 339.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1200
    height: 680
    depth_scale: 6553.5 #for depth image in png format
    distorted: False
    crop: 0
    ignore_edge: 0
    resize_wh: [640, 360]

decoder:
  num_components: 10 # dimension of features
  resolutions: [0.1, 0.04]
  latent_dims: [64, 128, 256, 512]

segmentation:
  k_thresh: 0.15 # 0.006 # geo: 0.008 sem: 0.3
  seg_min_verts: 20 
  k_neigbor: 5
  thres_connect: [0.9, 0.8, 0.7, 0.6, 0.5] 
  thres_merge: 200 

Training:
  kf_inter: 10
  fix_ply: True # True False
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  mapping_itr_num: 30
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  edge_threshold: 4
  pose_window: 5
  rgb_boundary_threshold: 0.01
  spherical_harmonics: False # False True
  thres_vis_dis: 0.07 # 0.15   # distance threshold for visibility test
  depth_test: True
  discard_unseen: True 

opt_params:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  language_feat_lr: 0.01
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  
pipeline_params:
  convert_SHs_python: True
  compute_cov3D_python: False